### ISSUE TITLE
Rumble resolution

### ISSUE THREAD

**Issue by BrainlessConsumer** [jeanslack/Vidtuber#13]
## Thanks for taking the time to submit a bug report! Please include the following information:

**What operating system are you using?**
Archlinux

**What version of Videtuber are you using and how did you install or run it?**
1.1.6 AppImage

**Describe the bug**
Rumble downloads very quickly - video resolution is is very low and the video doesn't play correctly (audio is fine).
The recent vidtuber update allowed editing the yt-dlp arguments (thank you for that) and it turns out if I add a * to bestvideo that fixes the problem ("bestvideo*+bestaudio/best").

... in case someone wants to know

"/usr/bin/yt-dlp" --format "bestvideo*+bestaudio/best"   --progress-template "download-title:%(info.id)s-%(progress.eta)s" --newline --compat-options "youtube-dl" --ignore-errors --ignore-config --no-color --no-playlist --ffmpeg-location "/usr/bin/ffmpeg" --output "/home/user/Desktop/%(title).100s.%(ext)s"

**Comment by jeanslack** [comment]
If you were using Precompiled videos as the download mode, I think your issue has already been fixed in this [PR](#12 ) 

Please see this [reference](https://github.com/jeanslack/Vidtuber/blob/c2d52af02a143c04c7c0b42382c5134206af8387/vidtuber/vt_panels/youtubedl_ui.py#L133).

**Comment by BrainlessConsumer** [comment]
Correct I was using the default precompiled videos.
As of today the problem still occurs only with Rumble video, not youtube or anything else.
The Rumble issue began a few months ago.
Im sure you will fix it soon enough in a new release (thanks for that).
Until the release the "*" symbol works.
